config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import IndexView
from main.views_packs.blogpost_views.blogpost_views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, \
    BlogPostDeleteView, BlogPostUpdateView
from main.views_packs.client_views.client_views import ClientCreateView, ClientListView, ClientDeleteView, \
    ClientUpdateView
from main.views_packs.message_views.message_views import MessageListView, MessageCreateView, MessageDeleteView, \
    MessageUpdateView
from main.views_packs.mailing_views.mailing_views import MailingListView, MailingCreateView, MailingUpdateView, \
    MailingDetailView, MailingDeleteView
from main.views_packs.log_views.log_views import LogListView, LogDetailView

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),

    path('blogpost/', BlogPostListView.as_view(), name='blogpost'),
    path('blogpost/create', BlogPostCreateView.as_view(), name='create_blogpost'),
    path('blogpost/detail/<int:pk>/', BlogPostDetailView.as_view(), name='detail_blogpost'),
    path('blogpost/update/<int:pk>/', BlogPostUpdateView.as_view(), name='update_blogpost'),
    path('blogpost/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='delete_blogpost'),

    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/create', ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('message/', MessageListView.as_view(), name='message'),
    path('message/create/', MessageCreateView.as_view(), name='create_message'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('mailing/', MailingListView. as_view(), name='mailing'),
    path('mailing/create/', MailingCreateView. as_view(), name='create_mailing'),
    path('mailing/detail/<int:pk>/', MailingDetailView. as_view(), name='detail_mailing'),
    path('mailing/update/<int:pk>/', MailingUpdateView. as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>/', MailingDeleteView. as_view(), name='delete_mailing'),
    #
    path('log/', LogListView.as_view(), name='log'),
    path('log/detail/<int:pk>/', LogDetailView.as_view(), name='detail_log'),

]

main/models.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='Контактный email', unique=True)
    fullname = models.CharField(max_length=50, verbose_name='ФИО')
    comment = models.TextField(verbose_name='Комментарий')

    def __str__(self):

        return f'{self.email}'

    class Meta:

        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):

    FREQUENCY_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('running', 'Запущена'),
        ('completed', 'Завершена'),
    )

    title = models.CharField(max_length=60, verbose_name='Тема рассылки')
    mail_body = models.TextField(verbose_name='Тело письма')
    frequency = models.CharField(max_length=25, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default='created', verbose_name='Статус рассылки')
    clients = models.ManyToManyField('Client', verbose_name='Клиенты', related_name='mailings')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Message(models.Model):

    title = models.CharField(max_length=25, verbose_name='Тема рассылки')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Log(models.Model):

    STATUS_CHOICES = (
        ('success', 'Успешно'),
        ('error', 'Ошибка'),
    )
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение рассылки')
    timedata = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, verbose_name='Статус попытки')
    server_response = models.TextField(verbose_name='Ответ почтового сервера')

    def __str__(self):
        return f"Время рассылки: {self.timedata}"

    class Meta:
        verbose_name = "Лог"
        verbose_name_plural = "Логи"


class BlogPost(models.Model):

    title = models.CharField(max_length=200, verbose_name='Название')
    content = models.TextField(verbose_name='Текст поста')
    preview = models.ImageField(upload_to='images/', verbose_name='Изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

main/forms.py
from django import forms

from main.models import BlogPost, Client, Message, Mailing, Log


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ['email', 'fullname', 'comment']


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ('title', 'mailing')


class MailingForm(forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ['title', 'mail_body', 'frequency', 'status', 'clients']


class LogForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = '__all__'


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'preview', 'is_published']


class StyleFormMixin:
    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

main/views.py
from django.db.models import Count
from django.shortcuts import render
from django.views import generic

from main.models import Mailing, Client, BlogPost


def index(request):
    context = {
        'title': 'Главная страница'
    }
    return render(request, 'main/index.html')


class IndexView(generic.ListView):
    def get(self, request, *args, **kwargs):
        mailing_number = Mailing.objects.count()
        mailing_number_active = Mailing.objects.filter(
            status='running').count()
        unique_clients = Client.objects.annotate(mailing_num=Count('mailings')).filter(
            mailing_num__gt=0).count()
        blogpost = list(BlogPost.objects.filter(is_published=True).values_list('title', flat=True)[
                        :3])
        context = {
            'title': 'Сервис рассылок',
            'mailing_number': mailing_number,
            'mailing_number_active': mailing_number_active,
            'unique_clients': unique_clients,
            'blogpost': blogpost
        }
        return render(request, 'main/index.html', context)

main/templates/main/blogpost/blogpost_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-6">
                <div class="card-header">
                    <h2 class="card-title">
                        Удаление поста
                    </h2>
                </div>
                <div class="card-body">
                    Удалить пост "{{ object }}"?
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
                <div class="card-footer">
                    <a href="{% url 'main:detail_blogpost' object.pk %}">Отмена</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/blogpost/blogpost_create.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">

            <div class="col-6">
                <div class="card-header">
                    <h2 class="card-title">
                        Добавление поста
                    </h2>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success m-2"
                           value="{% if object %}Изменить{% else %}Добавить{% endif %}">
                </div>
                <div class="card-footer"><a href="{% url 'main:blogpost' %}" class="btn btn-secondary m-2"> &laquo; Назад</a></div>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/blogpost/blogpost_detail.html
{% extends 'main/base.html' %}
{% block content %}

    <h1 class="mt-5">{{ object.title }}</h1>
    <p class="lead">{{ object.content }}</p>
    <p><a href="{% url 'main:blogpost' %}" class="btn btn-secondary m-2"> &laquo; Назад</a> <a class="btn btn-danger" href="{% url 'main:delete_blogpost' object.pk %}" role="button">Удалить</a></p>

{% endblock %}

main/templates/main/blogpost/blogpost_list.html
{% extends 'main/base.html' %}
{% load my_tags %}

{% block content %}

    <div class="text-center">


        <a class="btn btn-outline-primary" role="button" href="{% url 'main:create_blogpost' %}">Добавить пост</a>

    </div>
    {% for object in object_list %}
        <div class="col-md-5">
            <h2>{{ object.title }}</h2>
            <p>{{ object.content|truncatechars:100 }}</p>
            <p><a class="btn btn-secondary" href="{% url 'main:detail_blogpost' object.pk %}" role="button">Посмотреть &raquo; </a>  <a class="btn btn-outline-success" href="{% url 'main:update_blogpost' object.pk %}" role="button">Править</a></p>
          </div>
    {% endfor %}

{% endblock %}

main/templates/main/blogpost/blogpost_update.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">

            <div class="col-6">
                <div class="card-header">
                    <h2 class="card-title">
                        Добавление поста
                    </h2>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer">
                    <a href="{% url 'main:blogpost' %}" class="btn btn-secondary m-2"> &laquo; Назад</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}